"""RFC 8785 canonical JSON: official fixed Golden vectors + baseline regression.

Every expected canonical byte string below is a pre-fixed constant taken from
the RFC 8785 / ECMAScript ``Number::toString`` rules — never generated by the
implementation under test. The baseline regression is the second, independent
source of truth: T000's locked ``content_hash`` values were produced by the
project owner's toolchain, and must be reproduced exactly.
"""
from __future__ import annotations

import json
import struct
from pathlib import Path

import pytest

from ai_scientist_mvp.domain import canonical_json

ROOT = Path(__file__).resolve().parents[2]


# Fixed RFC 8785 canonical bytes: (python value, expected canonical UTF-8).
GOLDEN_VECTORS = [
    # numbers: ECMAScript Number::toString / JSON.stringify semantics
    (0.5, b"0.5"),
    (1e21, b"1e+21"),
    (1e-6, b"0.000001"),
    (1e-7, b"1e-7"),
    (-0.0, b"0"),
    (1.5, b"1.5"),
    (-1.25, b"-1.25"),
    (2.5e-3, b"0.0025"),
    # object key ordering (UTF-16 code units)
    ({"b": 1, "a": 2}, b'{"a":2,"b":1}'),
    # minimal string escaping (control characters)
    ("a\nb\tc", b'"a\\nb\\tc"'),
    # non-ASCII kept raw as UTF-8
    ({"k": "中"}, b'{"k":"\xe4\xb8\xad"}'),
    # UTF-16 key ordering places astral (U+1F600) before BMP U+E000,
    # unlike Unicode code-point order.
    ({chr(0x1F600): 1, chr(0xE000): 2}, b'{"\xf0\x9f\x98\x80":1,"\xee\x80\x80":2}'),
]

# RFC 8785 Appendix B finite IEEE-754 vectors, encoded by their binary64 bits.
APPENDIX_B_NUMBER_VECTORS = [
    ("0000000000000000", b"0"),
    ("8000000000000000", b"0"),
    ("0000000000000001", b"5e-324"),
    ("8000000000000001", b"-5e-324"),
    ("7fefffffffffffff", b"1.7976931348623157e+308"),
    ("ffefffffffffffff", b"-1.7976931348623157e+308"),
    ("4340000000000000", b"9007199254740992"),
    ("c340000000000000", b"-9007199254740992"),
    ("4430000000000000", b"295147905179352830000"),
    ("44b52d02c7e14af5", b"9.999999999999997e+22"),
    ("44b52d02c7e14af6", b"1e+23"),
    ("44b52d02c7e14af7", b"1.0000000000000001e+23"),
    ("444b1ae4d6e2ef4e", b"999999999999999700000"),
    ("444b1ae4d6e2ef4f", b"999999999999999900000"),
    ("444b1ae4d6e2ef50", b"1e+21"),
    ("3eb0c6f7a0b5ed8c", b"9.999999999999997e-7"),
    ("3eb0c6f7a0b5ed8d", b"0.000001"),
    ("41b3de4355555553", b"333333333.3333332"),
    ("41b3de4355555554", b"333333333.33333325"),
    ("41b3de4355555555", b"333333333.3333333"),
    ("41b3de4355555556", b"333333333.3333334"),
    ("41b3de4355555557", b"333333333.33333343"),
    ("becbf647612f3696", b"-0.0000033333333333333333"),
    ("43143ff3c1cb0959", b"1424953923781206.2"),
]


@pytest.mark.parametrize("value,expected", GOLDEN_VECTORS)
def test_rfc8785_golden_vectors(value, expected: bytes) -> None:
    assert canonical_json.canonicalize(value) == expected


@pytest.mark.parametrize("binary64_hex,expected", APPENDIX_B_NUMBER_VECTORS)
def test_rfc8785_appendix_b_number_vectors(binary64_hex: str, expected: bytes) -> None:
    value = struct.unpack(">d", bytes.fromhex(binary64_hex))[0]
    assert canonical_json.canonicalize(value) == expected


def test_nan_and_infinity_are_rejected() -> None:
    for bad in (float("nan"), float("inf"), float("-inf")):
        with pytest.raises(ValueError):
            canonical_json.canonicalize(bad)


def test_non_binary64_safe_integer_collision_is_rejected() -> None:
    safe = 9_007_199_254_740_992
    unsafe = 9_007_199_254_740_993
    assert canonical_json.canonicalize(safe) == b"9007199254740992"
    with pytest.raises(ValueError, match="not exactly representable"):
        canonical_json.canonicalize(unsafe)
    with pytest.raises(ValueError, match="not exactly representable"):
        canonical_json.content_hash({"nested": [unsafe]})


def test_non_json_inputs_have_stable_failures() -> None:
    with pytest.raises(TypeError, match="keys must be strings"):
        canonical_json.canonicalize({1: "not an object key"})
    with pytest.raises(TypeError, match="not a JSON-compatible type"):
        canonical_json.canonicalize((1, 2))
    with pytest.raises(ValueError, match="lone UTF-16 surrogate"):
        canonical_json.canonicalize("\ud800")

    cyclic: list[object] = []
    cyclic.append(cyclic)
    with pytest.raises(ValueError, match="cyclic containers"):
        canonical_json.canonicalize(cyclic)


def test_identity_critical_jcs_dependency_is_exactly_pinned() -> None:
    pyproject = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    assert '"jcs==0.2.1"' in pyproject


def _load(relative: str) -> dict:
    return json.loads((ROOT / relative).read_text(encoding="utf-8"))


def test_reproduces_locked_baseline_content_hash() -> None:
    lock = _load("governance/baseline.lock.json")
    assert canonical_json.content_hash_excluding(lock) == lock["content_hash"]


def test_reproduces_locked_decision_record_content_hashes() -> None:
    lock = _load("governance/baseline.lock.json")
    for record in lock["decision_records"]:
        obj = _load(record["ref"])
        assert canonical_json.content_hash_excluding(obj) == record["content_hash"], record["ref"]


def test_reproduces_locked_research_question_and_workflow_hashes() -> None:
    lock = _load("governance/baseline.lock.json")
    research_question = _load(lock["research_question"]["ref"])
    assert (
        canonical_json.content_hash_excluding(research_question)
        == lock["research_question"]["content_hash"]
    )
    workflow = _load(lock["workflow"]["ref"])
    assert canonical_json.content_hash_excluding(workflow) == lock["workflow"]["content_hash"]


def test_content_hash_excluding_removes_only_own_field() -> None:
    obj = {"a": 1, "content_hash": "x"}
    assert canonical_json.content_hash_excluding(obj) == canonical_json.content_hash({"a": 1})
